#===================================================================================
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com.cn
#===================================================================================

name: CI

on: [push]

env:
  INPUT_SLOT: esp32

jobs:
  build:
    strategy:
      matrix:
        os:
        - windows-2016
        - ubuntu-16.04
        - macos-latest
  
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2
      
    - name: Check action.py itself
      run: |
        sh script.sh
      shell: bash
    
    - name: Get the string
      id: hack_inisetup
      uses: ccccmagicboy/hack_inisetup@master
      with:
        slot: esp32

    - name: Print the result
      run: |
        echo ${{ steps.hack_inisetup.outputs.result }}
      shell: bash
        
        
        